/************************************************************************************
 * Copyright (c) 2019, Brillio
 * All rights reserved.
 * @author Brillio
 * @date 2019
 * @group Community
 * @description Class is created for handling Application related roles issues.
 ****************************************************************************************/
public with sharing class FNS_CommunityRelatedRoleController {
    /*@AuraEnabled
    public static List<FNS_RelatedRoles__c> fetchApplicationRelatedRoles(){
        List<FNS_RelatedRoles__c> relatedRoleList = new FNS_RelatedRolesSelector().selectRoleByOppId(new set<Id>{'0062E00001DNAaBQAX'});
        return relatedRoleList;
    }*/

}