/*****************************************************************************************
* @description This class act as a wrapper for HTTPResponse.
* @author Nidhi Chouksey
* @date 25/02/2019
* @Support Email Nidhi@comitydesigns.com
******************************************************************************************/
 public with sharing class FNS_ResponseWrapper {
      public String access_token;
      public String refresh_token;
      public Integer statusCode; 
 }