public with sharing class FNS_CollateralWrapper {
   
    public String agentPhone;
    public String fxAmt;
    public String fxRate;
    public String pledgedDate;
    public String requiredNumberOfDaysCoverage;
    public String description;
    public String appraiserName;
    public String insuranceType;
    public String valueAdvanceRate;
    public String insurancePolicyNumber;
    public String fxCode;
    public String purchasedDate;
    public String insuredAmount;
    public String appraisalDate;
    public String insuranceAmount;
    public String valueAdvanceRateMax;
    public Integer valueFairMarket;
    public String hostNumber;
    public String appraisalRequired;
    public String appraiserPhone;
    public String agentName;
    public String premium_period_id;
    public String descriptionOfInsurance;
    public String valueDate;
    public String agencyName;
    public String otherCoverageTypeDescription;
    public String agencyPhone;
    public Integer typeId;
    public String category;
    public String valueSource;
    public Integer categoryId;
    
    public Address address;
    public List<String> entityIds;
	public List<String> loanIds;
}