/*****************************************************************************************
* @description Class is used to handle all request from FNS_trackingItems.cmp.
* @author Praneeth Aitharaju
* @date 29/04/2019
* @Support Email praneeth.aitharaju@comitydesigns.com
******************************************************************************************/
public with sharing class FNS_DocumentUploadPayload {

	public Integer applicationId;	//100025
	public Integer collateralId;	//343444
	public String contentAddedDate;	//2019-03-03T12:30:52Z
	public String contentDirectory;	//string
	public String covenantTrackingId;	//string
	public String crwId;	//string
	public boolean csa;
	public Integer customerId;	//313123
	public String description;	//Receipt of Disclosures
	public Integer documentId;	//43344
	public String documentType;	//Acknowledgement of receipt of Disclosures
	public String externalDocumentId;	//string
	public Integer loanId;	//334344
	public Integer printOrderId;	//344
	public Integer statusId;	//123
	public boolean systemAdded;
	public Integer trackingItemId;	//79877
	public Integer userId;	//8973773
	public boolean visible;
}